name: my-first-workflow 

on: [push]

jobs:
    first_job:
        runs-on: ubuntu:latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                  repository: https://github.com/waditya/actions-01
            - name: Welcome Message
              run: echo "My first GitHub Action Job"
            
            - name: List Files
              run: ls

            - name: Read file
              run: cat README.md
              

